spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://maildb/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true