spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    initialization-mode: embedded
  mail:
    host: ${MAIL_SERVER:localhost}
    port: ${MAIL_SERVER_PORT:25}
    username: ${MAIL:admin@murcy.es}
    password: ${MAIL_PASSWORD:passwd123}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:false}
          starttls.enable: ${MAIL_TTLS:false}
murcy:
  api-key: ${API_KEY:secretapikey}
